### Send POST request with json body
POST http://localhost:8080/api/login
Content-Type: application/json; charset=utf-8

{"username":"kali","password":"123456","id":"216456628","uuid":"OWFlNTA4YjQtZWVjYy00MjU0LThiYmItNTRjYjVmYTRkNDJl","autoLogin":true,"type":"account","deviceInfo":{"os":"windows","type":"client","name":"desktop-s11sceo"}}

### logout
POST http://localhost:8080/api/logout
Content-Type: application/json; charset=utf-8
Authorization: Bearer QkW914xymEh20atplVjAA8ZQ1tsKJcw3hmM7paj2ZSg=

{"id":"216456628","uuid":"OWFlNTA4YjQtZWVjYy00MjU0LThiYmItNTRjYjVmYTRkNDJl"}

### currentUser
POST http://localhost:8080/api/currentUser
Content-Type: application/json; charset=utf-8
Authorization: Bearer QkW914xymEh20atplVjAA8ZQ1tsKJcw3hmM7paj2ZSg=

{"id":"216456628","uuid":"OWFlNTA4YjQtZWVjYy00MjU0LThiYmItNTRjYjVmYTRkNDJl"}

### ab
GET http://localhost:8080/api/ab
Content-Type: application/json; charset=utf-8
Authorization: Bearer yC37jv8ZJXufyIXa-2LuxKVp1pcpPdFHgVAR9-aFRcA=
