/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  audit_baselogs: () => import("@/views/audit/baseLogs/index.vue"),
  audit_filetransferlogs: () => import("@/views/audit/fileTransferLogs/index.vue"),
  home: () => import("@/views/home/index.vue"),
  system_mail_logs: () => import("@/views/system/mail_logs/index.vue"),
  system_mail_template: () => import("@/views/system/mail_template/index.vue"),
  user_list: () => import("@/views/user/list/index.vue"),
  user_sessions: () => import("@/views/user/sessions/index.vue"),
};
