/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      icon: 'ph:warning-bold',
      i18nKey: 'route.audit',
      order: 3
    },
    children: [
      {
        name: 'audit_baselogs',
        path: '/audit/baselogs',
        component: 'view.audit_baselogs',
        meta: {
          title: 'audit_baselogs',
          i18nKey: 'route.audit_baselogs',
          icon: 'hugeicons:files-01'
        }
      },
      {
        name: 'audit_filetransferlogs',
        path: '/audit/filetransferlogs',
        component: 'view.audit_filetransferlogs',
        meta: {
          title: 'audit_filetransferlogs',
          i18nKey: 'route.audit_filetransferlogs',
          icon: 'solar:square-transfer-horizontal-linear',
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'hugeicons:system-update-01',
      order: 4
    },
    children: [
      {
        name: 'system_mail',
        path: '/system/mail',
        meta: {
          title: 'system_mail',
          i18nKey: 'route.system_mail'
        },
        children: [
          {
            name: 'system_mail_logs',
            path: '/system/mail/logs',
            component: 'view.system_mail_logs',
            meta: {
              title: 'system_mail_logs',
              i18nKey: 'route.system_mail_logs',
              icon: 'icon-park-outline:upload-logs'
            }
          },
          {
            name: 'system_mail_template',
            path: '/system/mail/template',
            component: 'view.system_mail_template',
            meta: {
              title: 'system_mail_template',
              i18nKey: 'route.system_mail_template',
              icon: 'fluent:mail-template-16-regular'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      icon: 'majesticons:users-line',
      i18nKey: 'route.user',
      order: 2
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list',
          requiresAuth: true,
          icon: 'gravity-ui:person'
        }
      },
      {
        name: 'user_sessions',
        path: '/user/sessions',
        component: 'view.user_sessions',
        meta: {
          title: 'user_sessions',
          i18nKey: 'route.user_sessions',
          requiresAuth: true,
          icon: 'carbon:mobile-session'
        }
      }
    ]
  }
];
