on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: setup go env
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.1'

      - name: install
        run: |
          sudo apt update
          sudo apt install make zip -y
          npm install -g pnpm
          cd soybean-admin && pnpm i
      
      - name: build
        run: |
          go env -w GOOS=${{matrix.os}}
          go env -w GOARCH=${{matrix.arch}}
          go build -C backend -o ../build/
          cd soybean-admin && pnpm build 
          cd .. && cp -R soybean-admin/dist build/
          cp backend/server.yaml build/

      - name: pack files
        run: |
          zip ${{matrix.os}}-${{matrix.arch}}.zip build/*

      - name: create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{matrix.os}}-${{matrix.arch}}.zip
          
